const pages=[
	{//02
		title:"メンテナンスのお知らせ",//ページタイトル
		url:"maintenance.html",//ページURL
		keywords:["メンテナンス"]//検索ワード(AND検索、順不同)
	},
	{
		title:"メンテナンスのお知らせ",//ページタイトル
		url:"maintenance.html",//ページURL
		keywords:["メンテ"]//検索ワード(AND検索、順不同)
	},
	{//03
		title:"異邦神の園にボス『アラサラウス』が襲来！",//ページタイトル
		url:"event.html",//ページURL
		keywords:["アラサラウス"]//検索ワード(AND検索、順不同)
	},
	{
		title:"異邦神の園にボス『アラサラウス』が襲来！",//ページタイトル
		url:"event.html",//ページURL
		keywords:["異邦神の園"]//検索ワード(AND検索、順不同)
	},
	{//04
		title:"ワールドストーリー『予言の巫女編』が進行しました",//ページタイトル
		url:"worldstory.html",//ページURL
		keywords:["進行"]//検索ワード(AND検索、順不同)
	},
	{
		title:"ワールドストーリー『予言の巫女編』が進行しました",//ページタイトル
		url:"worldstory.html",//ページURL
		keywords:["ワールドストーリー"]//検索ワード(AND検索、順不同)
	},
	{
		title:"ワールドストーリー『予言の巫女編』が進行しました",//ページタイトル
		url:"worldstory.html",//ページURL
		keywords:["予言の巫女"]//検索ワード(AND検索、順不同)
	},
	{//05
		title:"ワールドストーリー【世界樹編】",//ページタイトル
		url:"worldtree.html",//ページURL
		keywords:["ワールドストーリー"]//検索ワード(AND検索、順不同)
	},
	{
		title:"ワールドストーリー【世界樹編】",//ページタイトル
		url:"worldtree.html",//ページURL
		keywords:["世界樹"]//検索ワード(AND検索、順不同)
	},
	{//06
		title:"ワールドストーリー【予言の巫女編】",//ページタイトル
		url:"predictor.html",//ページURL
		keywords:["ワールドストーリー"]//検索ワード(AND検索、順不同)
	},
	{
		title:"ワールドストーリー【予言の巫女編】",//ページタイトル
		url:"predictor.html",//ページURL
		keywords:["予言の巫女"]//検索ワード(AND検索、順不同)
	},
	{//07
		title:"ワールドストーリー【桜花の国編】",//ページタイトル
		url:"springcity.html",//ページURL
		keywords:["ワールドストーリー"]//検索ワード(AND検索、順不同)
	},
	{
		title:"ワールドストーリー【桜花の国編】",//ページタイトル
		url:"springcity.html",//ページURL
		keywords:["桜花の国"]//検索ワード(AND検索、順不同)
	},
	{//08
		title:"ワールドストーリー【煉獄界編】",//ページタイトル
		url:"helheim.html",//ページURL
		keywords:["ワールドストーリー"]//検索ワード(AND検索、順不同)
	},
	{
		title:"ワールドストーリー【煉獄界編】",//ページタイトル
		url:"helheim.html",//ページURL
		keywords:["煉獄界"]//検索ワード(AND検索、順不同)
	},
	{//09
		title:"サイドストーリー【魔女たちの物語】",//ページタイトル
		url:"witch.html",//ページURL
		keywords:["サイドストーリー"]//検索ワード(AND検索、順不同)
	},
	{
		title:"サイドストーリー【魔女たちの物語】",//ページタイトル
		url:"witch.html",//ページURL
		keywords:["魔女"]//検索ワード(AND検索、順不同)
	},
	{//10
		title:"サイドストーリー【人形の物語】",//ページタイトル
		url:"dole.html",//ページURL
		keywords:["サイドストーリー"]//検索ワード(AND検索、順不同)
	},
	{
		title:"サイドストーリー【人形の物語】",//ページタイトル
		url:"dole.html",//ページURL
		keywords:["人形"]//検索ワード(AND検索、順不同)
	},
	{//11
		title:"サイドストーリー【異邦神の物語/after】",//ページタイトル
		url:"foreigner-after.html",//ページURL
		keywords:["サイドストーリー"]//検索ワード(AND検索、順不同)
	},
	{
		title:"サイドストーリー【異邦神の物語/after】",//ページタイトル
		url:"foreigner-after.html",//ページURL
		keywords:["異邦神"]//検索ワード(AND検索、順不同)
	},
//Lv2
	{//12
		title:"カウンセリング記録",//ページタイトル
		url:"counseling.html",//ページURL
		keywords:["カウンセリング記録"]//検索ワード(AND検索、順不同)
	},
	{//13
		title:"ダミーアイテム「52756e65」について",//ページタイトル
		url:"dummyitem.html",//ページURL
		keywords:["52756e65"]//検索ワード(AND検索、順不同)
	},
	{//14・15・16
		title:"個人フォルダ：職員番号486f656e6972",//ページタイトル
		url:"486f656e6972.html",//ページURL
		keywords:["486f656e6972"],//検索ワード(AND検索、順不同)
		ngwords:["65696e6865726a6172"]//NGワード(1つでもあると除外)　未記入OK
	},
	{//17・18
		title:"個人フォルダ：職員番号4e6a6f726f72",//ページタイトル
		url:"4e6a6f726f72.html",//ページURL
		keywords:["4e6a6f726f72"],//検索ワード(AND検索、順不同)
		ngwords:["65696e6865726a6172"]//NGワード(1つでもあると除外)　未記入OK
	},
//Lv3
	{//19
		title:"研究報告",//ページタイトル
		url:"researchreport.html",//ページURL
		keywords:["タハティトルットゥ"]//検索ワード(AND検索、順不同)
	},
	{//20
		title:"第一種重要資料：束ねた首による魔術行使(抜粋版)",//ページタイトル
		url:"bundlednecks.html",//ページURL
		keywords:["4e6a6f726f72","束ねた首による魔術行使"]//検索ワード(AND検索、順不同)
	},
	{
		title:"第一種重要資料：束ねた首による魔術行使(抜粋版)",//ページタイトル
		url:"bundlednecks.html",//ページURL
		keywords:["4e6a6f726f72","束ねた首"]//検索ワード(AND検索、順不同)
	},
	{//21
		title:"第一種重要資料：不死の首(抜粋版)",//ページタイトル
		url:"immortalhead.html",//ページURL
		keywords:["4e6a6f726f72","不死の首"]//検索ワード(AND検索、順不同)
	},
	{//22
		title:"第一種重要資料：複写術(抜粋版)",//ページタイトル
		url:"copying.html",//ページURL
		keywords:["4e6a6f726f72","複写術"]//検索ワード(AND検索、順不同)
	},
	{//23
		title:"注文履歴",//ページタイトル
		url:"POrequest.html",//ページURL
		keywords:["パーフルオロカーボン"]//検索ワード(AND検索、順不同)
	},
	{//24
		title:"第二種重要資料：魔導血液(抜粋版)",//ページタイトル
		url:"magiticsolution.html",//ページURL
		keywords:["4e6a6f726f72","魔導血液"]//検索ワード(AND検索、順不同)
	},
	{//25
		title:"企業データ：ギョル牧場",//ページタイトル
		url:"ranch.html",//ページURL
		keywords:["ユグドラシルグループ","ギョル牧場"],//検索ワード(AND検索、順不同)
		ngwords:[""]//NGワード()1つでもあると除外　未記入OK
	},
	{//26
		title:"企業データ：ビフレスト製薬",//ページタイトル
		url:"pharmaceutical.html",//ページURL
		keywords:["ユグドラシルグループ","ビフレスト製薬"],//検索ワード(AND検索、順不同)
		ngwords:[""]//NGワード()1つでもあると除外　未記入OK
	},
	{//27
		title:"適合職員データ",//ページタイトル
		url:"compatibility.html",//ページURL
		keywords:["4e6a6f726f72","適合職員"]//検索ワード(AND検索、順不同)
	},
	{//28
		title:"個人フォルダ：職員番号6d696d6972",//ページタイトル
		url:"deleted.html",//ページURL
		keywords:["6d696d6972"],//検索ワード(AND検索、順不同)
		ngwords:["65696e6865726a6172"]//NGワード(1つでもあると除外)　未記入OK
	},
//Lv4
	{//29
		title:"適合職員：霜野美泉の処遇について",//ページタイトル
		url:"treatment.html",//ページURL
		keywords:["霜野美泉","管理部サーバー課"]//検索ワード(AND検索、順不同)
	},
	{
		title:"適合職員：霜野美泉の処遇について",//ページタイトル
		url:"treatment.html",//ページURL
		keywords:["霜野美泉","管理部","サーバー課"]//検索ワード(AND検索、順不同)
	},
	{//30
		title:"企業データ：ギンヌン・ガガプゲームス",//ページタイトル
		url:"games.html",//ページURL
		keywords:["ユグドラシルグループ","ギンヌン・ガガプゲームス"],//検索ワード(AND検索、順不同)
		ngwords:[""]//NGワード()1つでもあると除外　未記入OK
	},
	{//31
		title:"代表取締役担当者各位へ通達",//ページタイトル
		url:"notification.html",//ページURL
		keywords:["大典太出弦","代表取締役担当者"],//検索ワード(AND検索、順不同)
	},
	{//32
		title:"AMaSS取扱説明書",//ページタイトル
		url:"AMaSS.html",//ページURL
		keywords:["AMaSS"],//検索ワード(AND検索、順不同)
	},
	{//33
		title:"AMaSS実験結果",//ページタイトル
		url:"AMaSSresult.html",//ページURL
		keywords:["487567696e4d756e696e"],//検索ワード(AND検索、順不同)
	},
	{//34・35
		title:"処分結果報告書",//ページタイトル
		url:"disposalresult.html",//ページURL
		keywords:["476e69706168656c6c6972"],//検索ワード(AND検索、順不同)
	},
	{//36
		title:"対象がありません",//ページタイトル
		url:"notapplicable.html",//ページURL
		keywords:["65696e6865726a6172"],//検索ワード(AND検索、順不同)
		ngwords:["4e6a6f726f72","486f656e6972","6d696d6972"]//NGワード()1つでもあると除外　未記入OK
	},
//LvX
	{//37・38
		title:"個人フォルダ：職員番号486f656e6972(復元コード適用)",//ページタイトル
		url:"486f656e6972recovery.html",//ページURL
		keywords:["486f656e6972","65696e6865726a6172"]//検索ワード(AND検索、順不同)
	},
	{//39・40
		title:"個人フォルダ：職員番号4e6a6f726f72(復元コード適用)",//ページタイトル
		url:"4e6a6f726f72recovery.html",//ページURL
		keywords:["4e6a6f726f72","65696e6865726a6172"]//検索ワード(AND検索、順不同)
	},
	{//041・042・043
		title:"個人フォルダ：職員番号6d696d6972(復元コード適用)",//ページタイトル
		url:"6d696d6972.html",//ページURL
		keywords:["6d696d6972","65696e6865726a6172"]//検索ワード(AND検索、順不同)
	},
	{//44
		title:"名称変更のお知らせ",//ページタイトル
		url:"yggdrasill.html",//ページURL
		keywords:["GLEIPNIR"],//検索ワード(AND検索、順不同)
		ngwords:[""]//NGワード()1つでもあると除外　未記入OK
	},
	{//45
		title:"新聞記事",//ページタイトル
		url:"newspaper.html",//ページURL
		keywords:["GLEIPNIR"],//検索ワード(AND検索、順不同)
		ngwords:[""]//NGワード()1つでもあると除外　未記入OK
	},
	{//46
		title:"鍵",//ページタイトル
		url:"key.html",//ページURL
		keywords:["GLEIPNIR"],//検索ワード(AND検索、順不同)
		ngwords:[""]//NGワード()1つでもあると除外　未記入OK
	},
	{//47
		title:"道",//ページタイトル
		url:"road.html",//ページURL
		keywords:["GLEIPNIR"],//検索ワード(AND検索、順不同)
		ngwords:[""]//NGワード()1つでもあると除外　未記入OK
	},
	{//48
		title:"　",//ページタイトル
		url:"null.html",//ページURL
		keywords:["Ragnarøk"],//検索ワード(AND検索、順不同)
		ngwords:[""]//NGワード()1つでもあると除外　未記入OK
	},
	{
		title:"　",//ページタイトル
		url:"null.html",//ページURL
		keywords:["Ragnarök"],//検索ワード(AND検索、順不同)
		ngwords:[""]//NGワード()1つでもあると除外　未記入OK
	},
	{
		title:"　",//ページタイトル
		url:"null.html",//ページURL
		keywords:["Ragnarok"],//検索ワード(AND検索、順不同)
		ngwords:[""]//NGワード()1つでもあると除外　未記入OK
	},
	{
		title:"　",//ページタイトル
		url:"null.html",//ページURL
		keywords:["ラグナロク"],//検索ワード(AND検索、順不同)
		ngwords:[""]//NGワード()1つでもあると除外　未記入OK
	},
];
